// Decisions use a common positional snapshot. Safety and integration live in engine.mjs.
const clamp = (v, lo, hi) => Math.max(lo, Math.min(hi, v));
export function followingAcceleration(speed, gap, relativeSpeed, desiredGap, gain = 1) {return clamp(gain * .75 * (gap - desiredGap) + 1.6 * relativeSpeed, -5, 1.8);}
export function choosePath(rider, world) {const options=[rider.d,rider.d-1.15,rider.d+1.15,rider.d-2.3,rider.d+2.3].map(d=>clamp(d,.6,world.width-.6));return options.map(d=>{let space=45,blocked=false;for(const other of world.neighbors){if(Math.abs(other.d-d)<.9&&other.ds>-2&&other.ds<45){space=Math.min(space,Math.max(0,other.ds-1.9));if(other.ds<3)blocked=true;}}const occupiedByLine=(world.lineHeads??[]).some(h=>h.id!==rider.id&&Math.abs(h.s-rider.s)<25&&Math.abs(h.d-d)<1);return{d,space,score:Math.min(space,24)-Math.abs(d-rider.d)*.6-d*.7-(blocked?50:0)-(occupiedByLine?15:0)};}).sort((a,b)=>b.score-a.score)[0];}
function decideLeader(rider,world){const path=choosePath(rider,world),rivals=world.lineHeads.filter(r=>r.id!==rider.id),ahead=rivals.filter(r=>r.s>rider.s).sort((a,b)=>a.s-b.s)[0],alongside=rivals.some(r=>Math.abs(r.s-rider.s)<8&&Math.abs(r.d-rider.d)>.7),congested=world.obstacle&&world.obstacle.gap<rider.desiredGap+2,pressure=ahead?ahead.s-rider.s:0,phase=world.phase.id,late=['C','D','E','F'].includes(phase),support=world.lineMembers.filter(r=>r.id!==rider.id),stretched=support.some(r=>rider.s-r.s>20),pacerSpace=world.pacer.s-rider.s;if(stretched&&['B','C'].includes(phase))rider.action='DROP';else if(late&&path.space>9&&(pressure>6||alongside&&ahead&&rider.v>ahead.v+.3||!ahead&&world.remaining<600))rider.action='ATTACK';else if(congested&&path.space<6&&alongside)rider.action='DROP';else if((phase!=='A'&&pressure>5||phase==='B'&&pacerSpace>15)&&path.space>5)rider.action='ADVANCE';else rider.action='HOLD';if(rider.action==='ATTACK'||rider.action==='ADVANCE')rider.targetD=path.d;else if(rider.action==='DROP')rider.targetD=rider.d;if(world.time>6&&rivals.some(h=>Math.abs(h.s-rider.s)<25&&Math.abs(h.d-rider.d)<1))rider.targetD=path.d;}
export function lineController(rider,world,random){if(world.time<rider.reactionDelay)return{acceleration:0,lateral:0};rider.desiredGap=.9+rider.v*.15+rider.gapOffset;
 // Before the pacer releases the field, every rider follows the exact rider
 // immediately ahead at a deliberately large visual gap. This keeps the
 // oversized board-game bicycle pieces from overlapping while preserving one file.
 if(world.pacer.state==='guiding'){
   rider.targetD=world.pacer.d;
   const ahead=world.guideAhead;
   let acceleration=clamp((13.2-rider.v)*.8,-5,1.8);
   if(ahead){const desiredGap=Math.max(1.2,world.guidedCenterGap-1.9);acceleration=Math.min(acceleration,followingAcceleration(rider.v,ahead.gap,ahead.relativeSpeed,desiredGap,1.15));}
   if(world.obstacle) acceleration=Math.min(acceleration,followingAcceleration(rider.v,world.obstacle.gap,world.obstacle.relativeSpeed,1.2+rider.v*.12,rider.response));
   const lateral=clamp((world.pacer.d-rider.d)*1.1,-.55,.55);
   return{acceleration,lateral};
 }
 if(world.time>=rider.nextDecision){rider.nextDecision=world.time+.8+random()*1.1;rider.lastDecision=world.time;rider.decisionPhase=world.phase.id;rider.speedOffset=(random()-.5)*.7;rider.gapOffset=(random()-.5)*.35;rider.response=.85+random()*.3;rider.cohesion=clamp(world.remaining/200,0,1);if(rider.role==='leader')decideLeader(rider,world);else if(rider.cohesion<.85&&world.obstacle&&world.obstacle.gap<rider.desiredGap+3)rider.targetD=choosePath(rider,world).d;}
 let cruise=14.2;if(rider.role==='leader')cruise+=({HOLD:0,ADVANCE:.9,DROP:-1.7,ATTACK:2.8})[rider.action];else cruise+=3.6;cruise+=(1-rider.cohesion)*2.5+rider.speedOffset;let acceleration=clamp((cruise-rider.v)*.8,-5,1.8);const target=world.front;if(target){const follow=followingAcceleration(rider.v,target.gap,target.relativeSpeed,rider.desiredGap,rider.response),weight=rider.role==='leader'?1:rider.cohesion;acceleration=Math.min(acceleration,weight*follow+(1-weight)*acceleration);if(rider.role!=='leader'&&rider.cohesion>=.85)rider.targetD=world.baseTarget.d;}if(world.obstacle)acceleration=Math.min(acceleration,followingAcceleration(rider.v,world.obstacle.gap,world.obstacle.relativeSpeed,.7+rider.v*.12,rider.response));rider.targetD=clamp(rider.targetD,.55,world.width-.55);let lateral=clamp((rider.targetD-rider.d)*.75,-.55,.55);if(world.mergeBlocked(lateral))lateral=0;return{acceleration,lateral};}
export const toyController=lineController;
